#!/bin/bash
# git-version 
# Build a file containing version information from GIT
# (c) Copyright 2015 epsilonRT                
# All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License")

usage()
{
  echo "$0 filename.ext"
  echo "    extension provided (.ext) must be .h (for build C/C++ Header) or .mk (for Makefile)"
  echo 
}

if [ $# -lt 1 ]; then
  echo "$0 error: you must provide the name of the file to be created"
  usage
  exit -1
fi

OUTPUT=${1}
EXT=${OUTPUT##*.}
STAMP=.version
HASGIT=0

if [ -x "$(command -v git 2> /dev/null)" ]; then
  VERSION="$(git describe 2> /dev/null)"
  if [ $? -eq 0 ]; then
    HASGIT=1
    VERSION=${VERSION#v}
    VERSION=${VERSION#V}
  else
    echo "$0 error: git failed to find the project version !"
    usage
  fi
fi

if [ $HASGIT -eq 0 ]; then
  VERSION="1.0-0"
fi

if [ $HASGIT -eq 1 ]; then
  echo "the project git version is $VERSION"
  echo "$VERSION" > ${STAMP}
else
  echo "a default project version number will used ($VERSION)"
  # Version par défaut, le fichier .version est vide
  echo -n > ${STAMP}
fi

VERSION_SHORT=${VERSION%%-g*}
VERSION_SHORT_DOT=${VERSION_SHORT//-/.}
VERSION_TINY=${VERSION%%-*}

case "$EXT" in

  h)  VERSION_CORE=${VERSION_SHORT%%-*}
      VERSION_MAJOR=${VERSION_SHORT%%.*}
      VERSION_MAJOR=${VERSION_MAJOR%%[A-Za-z]*}
      VERSION_MINOR=${VERSION_CORE##*.}
      VERSION_MINOR=${VERSION_MINOR%%[A-Za-z]*}
      VERSION_PATCH=${VERSION_SHORT##*-}
      VERSION_PATCH=${VERSION_PATCH%%[A-Za-z]*}
      echo "#define VERSION \"$VERSION\"" > ${OUTPUT}
      echo "#define VERSION_SHORT \"$VERSION_SHORT_DOT\"" >> ${OUTPUT}
      echo "#define VERSION_TINY \"$VERSION_TINY\"" >> ${OUTPUT}
      echo "#define VERSION_MAJOR $VERSION_MAJOR" >> ${OUTPUT}
      echo "#define VERSION_MINOR $VERSION_MINOR" >> ${OUTPUT}
      echo "#define VERSION_PATCH $VERSION_PATCH" >> ${OUTPUT}
      if [[ $VERSION == *-g* ]]; then
        echo "#define VERSION_SHA1 0x${VERSION##*-g}" >> ${OUTPUT}
      else
        echo "#define VERSION_SHA1 0x0" >> ${OUTPUT}
      fi
      ;;
  mk) VERSION=${VERSION%%-*}
      echo "$VERSION_SHORT_DOT" > ${OUTPUT}
      ;;
  *)  echo "$0 error: unknown file extension !"
      usage
      exit -1
      ;;
esac
#echo "$OUTPUT generate for $VERSION version"
#cat ${OUTPUT}
exit 0
